# Generated by Django 4.2.3 on 2023-07-07 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='desct', max_length=1000),
        ),
        migrations.AddField(
            model_name='listing',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('RECORDS', 'Disques'), ('CLOTHING', 'Vetements'), ('POSTERS', 'Affiches'), ('MISCELLANEOUS', 'Divers')], default='MISCELLANEOUS', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default=2000, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='aaa', max_length=100),
        ),
    ]
