# Generated by Django 4.2.3 on 2023-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_description_listing_issold_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='desc', max_length=1000),
        ),
    ]
