# Generated by Django 4.2.3 on 2023-07-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='band',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
